CREATE TABLE IF NOT EXISTS mpp_paid_actions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  action_type TEXT NOT NULL,
  platform TEXT NULL,
  handle TEXT NULL,
  amount_usd TEXT NULL,
  status TEXT NOT NULL,
  correlation_id TEXT NOT NULL,
  meta JSONB NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS idx_mpp_paid_actions_created_at
  ON mpp_paid_actions(created_at DESC);

CREATE INDEX IF NOT EXISTS idx_mpp_paid_actions_correlation
  ON mpp_paid_actions(correlation_id);

CREATE INDEX IF NOT EXISTS idx_mpp_paid_actions_action_status
  ON mpp_paid_actions(action_type, status);

ALTER TABLE mpp_paid_actions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "mpp_paid_actions_read_authenticated" ON mpp_paid_actions;
CREATE POLICY "mpp_paid_actions_read_authenticated"
  ON mpp_paid_actions
  FOR SELECT
  TO authenticated
  USING (true);
