CREATE TABLE IF NOT EXISTS zktls_flow_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  correlation_id TEXT NOT NULL,
  idempotency_key TEXT NULL,
  stage TEXT NOT NULL,
  status TEXT NOT NULL,
  platform TEXT NULL,
  handle TEXT NULL,
  chain_id TEXT NULL,
  contract_address TEXT NULL,
  payment_id TEXT NULL,
  meta JSONB NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS idx_zktls_flow_events_created_at
  ON zktls_flow_events(created_at DESC);

CREATE INDEX IF NOT EXISTS idx_zktls_flow_events_correlation
  ON zktls_flow_events(correlation_id);

CREATE INDEX IF NOT EXISTS idx_zktls_flow_events_stage_status
  ON zktls_flow_events(stage, status);

ALTER TABLE zktls_flow_events ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "zktls_flow_events_read_authenticated" ON zktls_flow_events;
CREATE POLICY "zktls_flow_events_read_authenticated"
  ON zktls_flow_events
  FOR SELECT
  TO authenticated
  USING (true);
